apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobile-store
  namespace: shamil
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mobile-store
  template:
    metadata:
      labels:
        app: mobile-store
    spec:
      containers:
        - name: nginx-php
          image: harbor.strikerlulu.me/coding-strikerz/mobile-store:v3
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          # securityContext:
          #   runAsUser: 0
          env:
            - name: MYSQL_HOST
              value: mysql
          volumeMounts:
            - name: mobile-store-upload-volume
              mountPath: /var/www/html/uploads # Replace with the path where you want to mount the PV inside the container
      volumes:
        - name: mobile-store-upload-volume
          persistentVolumeClaim:
            claimName: mobile-store-uploads

