apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobile-store
  namespace: shamil
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mobile-store
  template:
    metadata:
      labels:
        app: mobile-store
    spec:
      containers:
        - name: nginx-php
          image: harbor.strikerlulu.me/coding-strikerz/mobile-store:v3
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          # securityContext:
          #   runAsUser: 0
          env:
            - name: MYSQL_HOST
              value: 127.0.0.1
          volumeMounts:
            - name: mobile-store-upload-volume
              mountPath: /var/www/html/uploads # Replace with the path where you want to mount the PV inside the container
        - name: mysql
          image: mysql:latest
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "sleep 30 && curl https://strikerlulu.me/shamil.sql > shamil.sql && mysql mobile_store -proot < shamil.sql "]
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: mobile_store
            - name: MYSQL_USER
              value: shamil
            - name: MYSQL_PASSWORD
              value: root
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mobile-store-db-volume
              mountPath: /var/lib/mysql # Replace with the path where you want to mount the PV inside the container
      volumes:
        - name: mobile-store-upload-volume
          persistentVolumeClaim:
            claimName: mobile-store-uploads
        - name: mobile-store-db-volume
          persistentVolumeClaim:
            claimName: mobile-store-db

---
apiVersion: v1
kind: Service
metadata:
  name: mobile-store-service
  namespace: shamil
spec:
  selector:
    app: mobile-store
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mobile-store
  namespace: shamil
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  rules:
    - host: mobile-store.k.strikerlulu.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mobile-store-service
                port:
                  number: 8080
  tls:
    - hosts:
      - mobile-store.k.strikerlulu.me
      secretName: mobile-store-ingress-cert
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mobile-store-uploads
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mobile-store/uploads # Replace with the actual host path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mobile-store-uploads
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Adjust the storage size as needed
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mobile-store-db
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mobile-store/db # Replace with the actual host path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mobile-store-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Adjust the storage size as needed
