name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

#       - name: Set up Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: '14'

#       - name: Install dependencies
#         run: npm install

      - name: Generate tag
        id: generate_tag
        run: echo "::set-output name=TAG::$(git rev-parse --short HEAD)"

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t harbor.strikerlulu.me/coding-strikerz/mobile-store:${{ steps.generate_tag.outputs.TAG }} .
          docker push harbor.strikerlulu.me/coding-strikerz/mobile-store:${{ steps.generate_tag.outputs.TAG }}

      - name: Configure Kubernetes cluster
        run: |
          echo "$KUBECONFIG" | base64 --decode > kubeconfig.yaml

      - name: Update image tag in deployment.yml
        run: |
          sed -i "s|image: harbor.strikerlulu.me/coding-strikerz/mobile-store:.*|image: harbor.strikerlulu.me/coding-strikerz/mobile-store:${{ steps.generate_tag.outputs.TAG }}|" deployment.yml

      - name: Deploy to Kubernetes
        uses: appleboy/kubectl-action@v1
        with:
          args: apply -f deployment.yaml --kubeconfig=kubeconfig.yaml

